name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "c9a60e2b968441ef8bb140a5ca6f35a1" },
  { binding = "SHARE", id = "3d3779a92b94495cb24d659ced73b8bd" }
]